### ISSUE TITLE
Nullable fields generating broken field implementations

### ISSUE THREAD

**Issue by craiglabenz** [odroe/prisma-dart#23]
While running the `User` /  `Post` example in the README, I've encountered a problem with the initial generated code.

It seems that nullable fields (e.g., `name String?`) generate the following Dart code:

```dart
final _i2.PrismaNullable<_i2.PrismaUnion<StringNullableWithAggregatesFilter, String, _i2.PrismaNull>> name;
```

Which breaks, because the class definition for `PrismaUnion` accepts 2 type parameters

```dart
class PrismaUnion<T0, T1> {}
```

Yet we've provided three

```dart
PrismaUnion<StringNullableWithAggregatesFilter, String, _i2.PrismaNull>
```

**Comment by medz** [comment]
I checkedout a new branch to reproduce and will fix this.

**Comment by medz** [comment]
For this bug fix, I don't think the generated input object type should be `PrismaUnion` wrapped, just `StringNullableWithAggregatesFilter`.

However this is a breaking change and a separate test has been created for this issue.

It will be fixed in the `2.2.0` release after waiting for the CI to be added.

**Comment by medz** [comment]
[![image](https://user-images.githubusercontent.com/5564821/191192268-2a17ff1a-af20-4e96-93d0-1b70fb30809c.png)
](https://twitter.com/odroeinc/status/1572120340561809410)

**Comment by zeucxb** [comment]
@medz is it suppose to work with mongo schemas too?
